export const AUTH_DATA = 'AUTH_data'
export const ERROR_MSG = 'error_msg'
export const RECEIVE_USER = 'receive_user'
export const RESET_USER = 'reset_user'
export const RECEIVE_USER_LIST = 'receive_user_list'
export const RECEIVE_CHAT_LIST = 'receive_chat_list'
export const RECEIVE_CHAT_MSG = 'receive_chat_msg'
export const READ_COUNT_GET = 'read_count_get'